import { config } from "dotenv";
config({ path: ".env.local" });

import { awsCredentialsProvider } from "@vercel/functions/oidc";
import { Signer } from "@aws-sdk/rds-signer";
import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { eq, like } from "drizzle-orm";
import * as schema from "../src/lib/db/schema";
import { computeCommissionSplit } from "../src/lib/partners/commission";

/**
 * Seeds realistic demo data for the affiliate partner portal so the whole
 * flow can be clicked through end-to-end locally / in a preview env:
 *
 *   npm run db:seed-partners
 *
 * What it creates (all marked with demo sentinels, see CLEANUP below):
 *   - 2 partner orgs: "Acme Sales Group" (active, fully populated) and
 *     "Northstar Reps" (pending — use it to test the admin Approve flow).
 *   - 2 reps under Acme (one activated, one still "invited").
 *   - Org- and rep-level referral links.
 *   - 5 attributed clinics (mix of verified/pending, org- vs rep-referred).
 *   - A spread of transactions across today / last week / last month / older,
 *     with commission ledger entries generated by the REAL commission engine
 *     (`computeCommissionSplit`) so the math matches production exactly.
 *   - One recorded payout to a rep (so payout history isn't empty), with the
 *     rest of the commission left unpaid so balances and the admin payout flow
 *     have something to act on.
 *
 * Re-runnable: every run first deletes prior demo rows (by sentinel) and
 * re-inserts, so you always get a clean, predictable dataset.
 *
 * Signing in AS a partner: the portal resolves identity from the signed-in
 * Clerk user id. To log in and see the org/rep portal (not just the admin
 * views, which work regardless), set these to real Clerk test-user ids before
 * running so the demo accounts are linked to logins you control:
 *   DEMO_ORG_CLERK_USER_ID=user_xxx   (Acme org owner)
 *   DEMO_REP_CLERK_USER_ID=user_yyy   (Acme's activated rep)
 * Without them the demo accounts have no login, but admins still see all data.
 */

// --- Sentinels (anything matching these is treated as demo data) ----------
const DEMO_EMAIL_DOMAIN = "logosrx.test";
const DEMO_CLINIC_PREFIX = "demo_seed_clinic_";

// --- Tunable demo rates (basis points; 100 = 1%) --------------------------
const ACME_ORG_RATE_BPS = 1000; // 10%
const REP_ALEX_RATE_BPS = 400; // 4% (carved out of org's 10%)
const REP_JORDAN_RATE_BPS = 250; // 2.5%

const DAY_MS = 24 * 60 * 60 * 1000;
function daysAgo(n: number): Date {
  return new Date(Date.now() - n * DAY_MS);
}

function buildPool(): Pool {
  const signer = new Signer({
    hostname: process.env.PGHOST!,
    port: Number(process.env.PGPORT),
    username: process.env.PGUSER!,
    region: process.env.AWS_REGION!,
    credentials: awsCredentialsProvider({
      roleArn: process.env.AWS_ROLE_ARN!,
      clientConfig: { region: process.env.AWS_REGION! },
    }),
  });
  return new Pool({
    host: process.env.PGHOST!,
    user: process.env.PGUSER!,
    database: process.env.PGDATABASE || "postgres",
    password: () => signer.getAuthToken(),
    port: Number(process.env.PGPORT),
    ssl: { rejectUnauthorized: false },
    max: 2,
  });
}

type Db = ReturnType<typeof drizzle<typeof schema>>;

async function cleanup(db: Db) {
  // Deleting demo clinics cascades their transactions + commission entries.
  // Deleting demo orgs cascades reps, referral links, payouts, and any
  // remaining commission entries (org FK is ON DELETE CASCADE).
  await db
    .delete(schema.clinics)
    .where(like(schema.clinics.clerkUserId, `${DEMO_CLINIC_PREFIX}%`));
  await db
    .delete(schema.partnerOrgs)
    .where(like(schema.partnerOrgs.contactEmail, `%${DEMO_EMAIL_DOMAIN}`));
}

async function seed(db: Db) {
  const orgClerkId = process.env.DEMO_ORG_CLERK_USER_ID || null;
  const repClerkId = process.env.DEMO_REP_CLERK_USER_ID || null;

  // --- Orgs ---------------------------------------------------------------
  const [acme] = await db
    .insert(schema.partnerOrgs)
    .values({
      clerkUserId: orgClerkId,
      name: "Acme Sales Group",
      contactName: "Dana Reyes",
      contactEmail: `acme@${DEMO_EMAIL_DOMAIN}`,
      contactPhone: "(813) 555-0142",
      website: "https://acmesales.example",
      notes: "Demo seed — established sales group covering FL/GA.",
      status: "active",
      commissionRateBps: ACME_ORG_RATE_BPS,
      approvedAt: daysAgo(120),
      approvedBy: "demo-seed",
    })
    .returning({ id: schema.partnerOrgs.id });

  await db.insert(schema.partnerOrgs).values({
    name: "Northstar Reps",
    contactName: "Priya Nair",
    contactEmail: `northstar@${DEMO_EMAIL_DOMAIN}`,
    contactPhone: "(305) 555-0188",
    website: "https://northstar.example",
    notes: "Demo seed — pending application; use to test Approve.",
    status: "pending",
    commissionRateBps: 0,
  });

  // --- Reps (under Acme) --------------------------------------------------
  const [alex] = await db
    .insert(schema.partnerReps)
    .values({
      orgId: acme.id,
      clerkUserId: repClerkId,
      name: "Alex Johnson",
      email: `alex@${DEMO_EMAIL_DOMAIN}`,
      phone: "(813) 555-0170",
      status: "active",
      commissionRateBps: REP_ALEX_RATE_BPS,
      invitedAt: daysAgo(100),
      activatedAt: daysAgo(98),
    })
    .returning({ id: schema.partnerReps.id });

  const [jordan] = await db
    .insert(schema.partnerReps)
    .values({
      orgId: acme.id,
      name: "Jordan Lee",
      email: `jordan@${DEMO_EMAIL_DOMAIN}`,
      phone: "(727) 555-0155",
      // Active but never activated → renders as "Invited" in the UI.
      status: "active",
      commissionRateBps: REP_JORDAN_RATE_BPS,
      invitedAt: daysAgo(10),
    })
    .returning({ id: schema.partnerReps.id });

  // --- Referral links -----------------------------------------------------
  const [orgLink] = await db
    .insert(schema.referralLinks)
    .values({
      code: "demoacme01",
      orgId: acme.id,
      label: "Acme — main",
      clickCount: 64,
      signupCount: 2,
    })
    .returning({ id: schema.referralLinks.id });

  const [alexLink] = await db
    .insert(schema.referralLinks)
    .values({
      code: "demoalex02",
      orgId: acme.id,
      repId: alex.id,
      label: "Alex — conference",
      clickCount: 38,
      signupCount: 2,
    })
    .returning({ id: schema.referralLinks.id });

  const [jordanLink] = await db
    .insert(schema.referralLinks)
    .values({
      code: "demojordan3",
      orgId: acme.id,
      repId: jordan.id,
      label: "Jordan — outbound",
      clickCount: 12,
      signupCount: 1,
    })
    .returning({ id: schema.referralLinks.id });

  // --- Attributed clinics -------------------------------------------------
  // [name, repId|null, linkId, verified, signupDaysAgo]
  const clinicSpecs: Array<{
    name: string;
    repId: number | null;
    linkId: number;
    verified: boolean;
    daysAgo: number;
  }> = [
    { name: "Bayshore Wellness", repId: null, linkId: orgLink.id, verified: true, daysAgo: 110 },
    { name: "Gulf Coast Vitality", repId: alex.id, linkId: alexLink.id, verified: true, daysAgo: 80 },
    { name: "Tampa Peak Health", repId: alex.id, linkId: alexLink.id, verified: false, daysAgo: 6 },
    { name: "Sunset Rejuvenation", repId: jordan.id, linkId: jordanLink.id, verified: true, daysAgo: 40 },
    { name: "Harbor Point Clinic", repId: null, linkId: orgLink.id, verified: false, daysAgo: 2 },
  ];

  const clinicIds: number[] = [];
  for (let i = 0; i < clinicSpecs.length; i++) {
    const spec = clinicSpecs[i];
    const [clinic] = await db
      .insert(schema.clinics)
      .values({
        clerkUserId: `${DEMO_CLINIC_PREFIX}${i + 1}`,
        clinicName: spec.name,
        contactName: `${spec.name} Admin`,
        contactEmail: `clinic${i + 1}@${DEMO_EMAIL_DOMAIN}`,
        contactPhone: "(813) 555-02" + String(10 + i),
        practiceType: "medical_spa",
        onboardingStep: 6,
        onboardingCompleted: true,
        verificationStatus: spec.verified ? "verified" : "pending",
        verifiedAt: spec.verified ? daysAgo(spec.daysAgo - 1) : null,
        referralLinkId: spec.linkId,
        partnerOrgId: acme.id,
        partnerRepId: spec.repId,
        createdAt: daysAgo(spec.daysAgo),
      })
      .returning({ id: schema.clinics.id });
    clinicIds.push(clinic.id);
  }

  // --- Transactions + commission ledger -----------------------------------
  // [clinicIndex, repRateBps|0, revenueDollars, daysAgo, ref]
  const txSpecs: Array<{
    clinicIdx: number;
    repId: number | null;
    repRateBps: number;
    revenue: number;
    daysAgo: number;
    ref: string;
  }> = [
    { clinicIdx: 0, repId: null, repRateBps: 0, revenue: 1850.0, daysAgo: 95, ref: "LF-40012" },
    { clinicIdx: 0, repId: null, repRateBps: 0, revenue: 2120.5, daysAgo: 3, ref: "LF-41880" },
    { clinicIdx: 1, repId: alex.id, repRateBps: REP_ALEX_RATE_BPS, revenue: 3400.0, daysAgo: 60, ref: "LF-40550" },
    { clinicIdx: 1, repId: alex.id, repRateBps: REP_ALEX_RATE_BPS, revenue: 1290.0, daysAgo: 2, ref: "LF-41902" },
    { clinicIdx: 2, repId: alex.id, repRateBps: REP_ALEX_RATE_BPS, revenue: 980.0, daysAgo: 1, ref: "LF-41950" },
    { clinicIdx: 3, repId: jordan.id, repRateBps: REP_JORDAN_RATE_BPS, revenue: 5600.0, daysAgo: 35, ref: "LF-40780" },
    { clinicIdx: 3, repId: jordan.id, repRateBps: REP_JORDAN_RATE_BPS, revenue: 1440.0, daysAgo: 5, ref: "LF-41875" },
  ];

  // Collect rep-Alex's commission-entry ids so we can mark them paid below.
  const alexEntryIds: number[] = [];

  for (const spec of txSpecs) {
    const revenueCents = Math.round(spec.revenue * 100);
    const [tx] = await db
      .insert(schema.partnerTransactions)
      .values({
        clinicId: clinicIds[spec.clinicIdx],
        transactionDate: daysAgo(spec.daysAgo),
        description: "Compounded order",
        reference: spec.ref,
        revenueCents,
        source: "manual",
        createdBy: "demo-seed",
        createdAt: daysAgo(spec.daysAgo),
      })
      .returning({ id: schema.partnerTransactions.id });

    const split = computeCommissionSplit({
      revenueCents,
      orgRateBps: ACME_ORG_RATE_BPS,
      repRateBps: spec.repRateBps,
    });

    for (const entry of split) {
      const [row] = await db
        .insert(schema.commissionEntries)
        .values({
          transactionId: tx.id,
          orgId: acme.id,
          repId: entry.payee === "rep" ? spec.repId : null,
          payee: entry.payee,
          rateBps: entry.rateBps,
          amountCents: entry.amountCents,
          status: "pending",
          createdAt: daysAgo(spec.daysAgo),
        })
        .returning({ id: schema.commissionEntries.id });
      if (entry.payee === "rep" && spec.repId === alex.id) {
        alexEntryIds.push(row.id);
      }
    }
  }

  // --- One historical payout to rep Alex (marks his entries paid) ---------
  if (alexEntryIds.length > 0) {
    const paidEntries = await db
      .select({
        id: schema.commissionEntries.id,
        amountCents: schema.commissionEntries.amountCents,
      })
      .from(schema.commissionEntries)
      .where(eq(schema.commissionEntries.repId, alex.id));
    const amountCents = paidEntries
      // Pay out only the older half so a fresh unpaid balance remains.
      .slice(0, Math.ceil(paidEntries.length / 2))
      .reduce((sum, e) => sum + e.amountCents, 0);
    const payIds = paidEntries
      .slice(0, Math.ceil(paidEntries.length / 2))
      .map((e) => e.id);

    if (amountCents > 0) {
      const [payout] = await db
        .insert(schema.payouts)
        .values({
          orgId: acme.id,
          repId: alex.id,
          payee: "rep",
          amountCents,
          method: "ach",
          reference: "DEMO-ACH-0001",
          notes: "Demo seed payout.",
          paidAt: daysAgo(14),
          recordedBy: "demo-seed",
          recordedByEmail: "seed@logosrx.test",
        })
        .returning({ id: schema.payouts.id });

      for (const id of payIds) {
        await db
          .update(schema.commissionEntries)
          .set({ status: "paid", payoutId: payout.id })
          .where(eq(schema.commissionEntries.id, id));
      }
    }
  }

  return {
    orgId: acme.id,
    orgLinked: Boolean(orgClerkId),
    repLinked: Boolean(repClerkId),
    clinicCount: clinicIds.length,
    txCount: txSpecs.length,
  };
}

async function main() {
  const pool = buildPool();
  const db = drizzle(pool, { schema });

  const meta = await pool.query(
    "select current_database() as db, current_user as usr",
  );
  console.log(`Connected to ${meta.rows[0].db} as ${meta.rows[0].usr}\n`);

  console.log("Clearing prior demo data…");
  await cleanup(db);

  console.log("Seeding partner demo data…");
  const result = await seed(db);

  await pool.end();

  console.log("\nDone. Seeded:");
  console.log(`  • 2 partner orgs (1 active "Acme Sales Group", 1 pending "Northstar Reps")`);
  console.log(`  • 2 reps under Acme (Alex activated, Jordan invited)`);
  console.log(`  • 3 referral links, ${result.clinicCount} attributed clinics, ${result.txCount} transactions`);
  console.log(`  • commission ledger + 1 historical rep payout`);
  console.log("\nWhere to look:");
  console.log("  • Admin: /admin/partners  →  open Acme to see reps, links, clinics, payouts");
  console.log("  • Admin: /admin/partners/transactions  →  add/import more, see the ledger");
  if (result.orgLinked || result.repLinked) {
    console.log("  • Partner portal: sign in as your linked Clerk user → /partners");
  } else {
    console.log(
      "  • To click the PARTNER side, set DEMO_ORG_CLERK_USER_ID / DEMO_REP_CLERK_USER_ID\n" +
        "    to real Clerk test-user ids and re-run, then sign in as that user → /partners",
    );
  }
}

main().catch((err) => {
  console.error("\nSeed failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
